spring:
  aplication:
    name: Api-clinica
  datasource:
    url: jdbc:oracle:thin:@//agregar medium
    password: //agregar
    driver-class-name: oracle.jdbc.OracleDriver
    jpa:
      database-plataform: org.hibernate.dialect.OracleDialect
      hibernate:
          ddl-auto: validate
        show-sql: true
server:
  port: 25001